In [1]:
from dotenv import load_dotenv
from pathlib import Path
import sys
import os

# Walk up until we find the project root (folder with the .env)
current_path = Path().resolve()
for parent in [current_path] + list(current_path.parents):
    if (parent / ".env").exists():
        load_dotenv(parent / ".env")
        project_root = os.getenv("PROJECT_ROOT")
        print(project_root)
        sys.path.append(project_root)     
        break


%load_ext autoreload
%autoreload 2

C:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\

Failed to read module file 'C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\pydoc_data\topics.py' for module 'pydoc_data.topics': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 4638: character maps to <undefined>
Failed to read module file 'C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\shlex.py' for module 'shlex': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1442: character maps to <undefined>
Failed to read module file 'C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\re\_casefix.py' for module 're._casefix': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 893: character maps to <undefined>
Failed to read module file 'C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\urllib\parse.py' for module 'urllib.parse': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1981: character maps to <undefined>
Failed to read module file 'C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\functools.py' for module 'functools': UnicodeDecodeError
Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 62, in load_extension
    return self._load_extension(module_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\core\extensions.py", line 77, in _load_extension
    mod = import_module(module_str)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'autoreload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\IPython\extensions\deduperreload\deduperreload.py", line 219, in update_sources
    self.source_by_modname[new_modname] = f.read()
                                          ^^^^^^^^
  File "C:\Users\Admin\AppData\Roaming\uv\python\cpython-3.12.8-windows-x86_64-none\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 301: character maps to <undefined>

In [2]:
import pandas as pd

import torch
from models.resnet import ResnetMultilabel
from models.mobilenet import MobileNetMultilabel
from models.quant_mobilenet import load_mobilenet_v3_quant

from training.cross_validation import run_cross_val, train_model

## Running the Optimization Experiments

This section covers the model optimization experiments:
- Switching from **ResNet18** to **MobileNet V3 Small**,
- Further **Truncating** the MobileNet architecture,
- Applying **8-bit Quantization-Aware Training (QAT)** on the MobileNet model.

Each experiment is executed with **cross-validation** as described in the paper.  
Results are written to a dedicated `results/` directory and subsequently examined in the `results_analysis` folder.

In [15]:
labels_df = pd.read_csv("../data/Verified_Dataset/labels/labels_merged.csv")
labels_df["ClipFilenamePt"] = labels_df["clip_filename"].str.replace(".wav", ".pt", regex=False)


label_columns = ["ECHO", "HFPC", "BBPC", "Whistle"]

data_dir = "../data"
processed_spects_dir = data_dir + "/Verified_Dataset/spectrograms/"

# labels_df =labels_df[labels_df["Boat"] != 1]
labels_df =labels_df[labels_df["labeling_effort"].isin(["old_abs_from_3s_snippets", "old_abs_CAC_last_samples", "irene_20min", "irene_5min"])]

labels_df.reset_index(drop=True, inplace=True)

results_dir = "./results/new_dataset"

In [16]:
labels_df[labels_df["HFPC"].isna()]

Empty DataFrame
Columns: [clip_filename, ECHO, BBPC, HFPC, Whistle, Call, Boat, labeling_effort, DETAIL, Begin Time (s), End Time (s), GROUNDTRUTH, Notes, original_filename, labeled_snippet_filename, snippet_start_time, snippet_start_s, snippet_end_s, Site, labeled_snippet_dir, HydrophoneModel, HydrophoneSensitivity, clip_start_time, clip_end_time, DETAILS, boat_labeling_file, boat_labeling_file_id, annotator, SnippetFilename, start_s, end_s, ClipFilenamePt]
Index: []

[0 rows x 32 columns]

In [17]:
training_config_default = {
    "batch_size": 32,
    "lr_decay_factor": 0.5,
    "patience_lr": 2,
    # "n_epochs": 1, #100
    # "min_epochs": 0, #15
    "n_epochs": 100, #100
    "min_epochs": 10, #15
    "patience_early_stopping": 5,
    "metric_mode": "max",
    "val_metric": "f1",
}

In [18]:
import torch
torch.cuda.is_available()

True

### Resnet18

In [19]:
run_cross_val(
    labels_df, 
    label_columns, 
    ResnetMultilabel,  
    processed_spects_dir,
    run_name="resnet_only_irene",
    results_dir=results_dir,
    model_kwargs={
        "pretrained":True,
    }, 
    training_config=training_config_default,
    save_models=True,
    use_quantization=False,
)

Val Epoch: 20

100%|██████████| 42/42 [00:03<00:00, 12.33it/s]

Val Epoch: 20 Results -
loss: 9.618,
accuracy: {'Labels_Average': 0.9836219549179077, 'ECHO': 0.9804216623306274, 'HFPC': 0.9871987700462341, 'BBPC': 0.9849397540092468, 'Whistle': 0.9819276928901672},
f1: {'Labels_Average': 0.901005744934082, 'ECHO': 0.8879310488700867, 'HFPC': 0.882758617401123, 'BBPC': 0.9047619104385376, 'Whistle': 0.9285714030265808},
precision: {'Labels_Average': 0.9237242937088013, 'ECHO': 0.8728813529014587, 'HFPC': 0.9014084339141846, 'BBPC': 0.9693877696990967, 'Whistle': 0.9512194991111755},
recall: {'Labels_Average': 0.8808912038803101, 'ECHO': 0.9035087823867798, 'HFPC': 0.8648648858070374, 'BBPC': 0.8482142686843872, 'Whistle': 0.9069767594337463},
AUC: {'Labels_Average': 0.9961872100830078, 'ECHO': 0.9949095249176025, 'HFPC': 0.996605396270752, 'BBPC': 0.9970262050628662, 'Whistle': 0.9962078332901001},
exact_match: {'Labels_Average': 0.946536123752594},

Training Epoch: 21

100%|██████████| 166/166 [00:20<00:00,  8.10it/s]

Train Epoch: 21 Results -
loss: 0.463,
accuracy: {'Labels_Average': 0.9990110993385315, 'ECHO': 0.999058187007904, 'HFPC': 0.9992465376853943, 'BBPC': 0.9992465376853943, 'Whistle': 0.9984931349754333},
f1: {'Labels_Average': 0.9949530363082886, 'ECHO': 0.995112419128418, 'HFPC': 0.9943820238113403, 'BBPC': 0.9953810572624207, 'Whistle': 0.9949367046356201},
precision: {'Labels_Average': 0.9966465830802917, 'ECHO': 0.998039186000824, 'HFPC': 0.997183084487915, 'BBPC': 0.9976851940155029, 'Whistle': 0.993678867816925},
recall: {'Labels_Average': 0.9932711720466614, 'ECHO': 0.9922027587890625, 'HFPC': 0.9915966391563416, 'BBPC': 0.9930875301361084, 'Whistle': 0.9961977005004883},
AUC: {'Labels_Average': 0.999971866607666, 'ECHO': 0.9999910593032837, 'HFPC': 0.9999406337738037, 'BBPC': 0.9999645352363586, 'Whistle': 0.9999910593032837},
exact_match: {'Labels_Average': 0.996232807636261},

Val Epoch: 21

100%|██████████| 42/42 [00:03<00:00, 12.31it/s]

Val Epoch: 21 Results -
loss: 9.655,
accuracy: {'Labels_Average': 0.9821159839630127, 'ECHO': 0.9796686768531799, 'HFPC': 0.9871987700462341, 'BBPC': 0.9849397540092468, 'Whistle': 0.9766566157341003},
f1: {'Labels_Average': 0.8942699432373047, 'ECHO': 0.8810572624206543, 'HFPC': 0.884353756904602, 'BBPC': 0.9047619104385376, 'Whistle': 0.9069069027900696},
precision: {'Labels_Average': 0.920660674571991, 'ECHO': 0.8849557638168335, 'HFPC': 0.8904109597206116, 'BBPC': 0.9693877696990967, 'Whistle': 0.9378882050514221},
recall: {'Labels_Average': 0.8704231381416321, 'ECHO': 0.8771929740905762, 'HFPC': 0.8783783912658691, 'BBPC': 0.8482142686843872, 'Whistle': 0.8779069781303406},
AUC: {'Labels_Average': 0.9960952997207642, 'ECHO': 0.9947469234466553, 'HFPC': 0.9963468313217163, 'BBPC': 0.9971877932548523, 'Whistle': 0.9960997104644775},
exact_match: {'Labels_Average': 0.9420180916786194},
No improvement over last 5 epochs in validation loss. Early stopping...
Training complete. Loading best model weights.
Training complete in 8m 47s

Test Epoch: 0

100%|██████████| 52/52 [00:05<00:00, 10.06it/s]

Test Epoch: 0 Results -
loss: 9.491,
accuracy: {'Labels_Average': 0.9805605411529541, 'ECHO': 0.9704641103744507, 'HFPC': 0.9825195670127869, 'BBPC': 0.9843279123306274, 'Whistle': 0.984930694103241},
f1: {'Labels_Average': 0.8829095959663391, 'ECHO': 0.8338983058929443, 'HFPC': 0.8379888534545898, 'BBPC': 0.912162184715271, 'Whistle': 0.947589099407196},
precision: {'Labels_Average': 0.8952045440673828, 'ECHO': 0.8601398468017578, 'HFPC': 0.8823529481887817, 'BBPC': 0.8766233921051025, 'Whistle': 0.9617021083831787},
recall: {'Labels_Average': 0.8729178309440613, 'ECHO': 0.8092105388641357, 'HFPC': 0.7978723645210266, 'BBPC': 0.9507042169570923, 'Whistle': 0.93388432264328},
AUC: {'Labels_Average': 0.9942170977592468, 'ECHO': 0.9898478388786316, 'HFPC': 0.9958534240722656, 'BBPC': 0.9959380030632019, 'Whistle': 0.9952291250228882},
exact_match: {'Labels_Average': 0.9324894547462463},
Final test loss: 9.4907
                   Filename Site  ECHO_true  ECHO_pred    ECHO_probs  \
0  BSM_20170724_10580200.pt  BSM        0.0        0.0  2.896608e-06
1  BSM_20170724_12500200.pt  BSM        0.0        0.0  4.422266e-07
2  BSM_20170724_12560100.pt  BSM        0.0        0.0  6.666681e-06
3  BSM_20170724_13090979.pt  BSM        0.0        0.0  2.534888e-02
4  BSM_20170724_13220150.pt  BSM        0.0        0.0  4.679000e-02

   HFPC_true  HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  \
0        0.0        0.0  3.461628e-08        0.0        0.0  8.896340e-08
1        0.0        0.0  1.570518e-09        0.0        0.0  4.144646e-08
2        0.0        0.0  2.871543e-08        0.0        0.0  1.901450e-05
3        1.0        1.0  9.936199e-01        0.0        0.0  1.287776e-01
4        1.0        1.0  9.695476e-01        0.0        0.0  1.085783e-06

   Whistle_true  Whistle_pred  Whistle_probs
0           0.0           0.0   5.900378e-07
1           0.0           0.0   8.026673e-10
2           0.0           0.0   4.330503e-07
3           1.0           1.0   9.854019e-01
4           0.0           0.0   1.471570e-04
Size (MB): 45.284346
Size (KB): 44222.994140625
Created test dataloader for site: KAM with 135 samples

Test on site kam Epoch: 0

100%|██████████| 5/5 [00:00<00:00, 11.28it/s]

Test on site kam Epoch: 0 Results -
loss: 26.759,
accuracy: {'Labels_Average': 0.9370370507240295, 'ECHO': 0.8888888955116272, 'HFPC': 0.9629629850387573, 'BBPC': 0.9629629850387573, 'Whistle': 0.9333333373069763},
f1: {'Labels_Average': 0.8772993087768555, 'ECHO': 0.8275862336158752, 'HFPC': 0.8148148059844971, 'BBPC': 0.9411764740943909, 'Whistle': 0.9256198406219482},
precision: {'Labels_Average': 0.8571294546127319, 'ECHO': 0.8571428656578064, 'HFPC': 0.7333333492279053, 'BBPC': 0.8888888955116272, 'Whistle': 0.9491525292396545},
recall: {'Labels_Average': 0.9049731492996216, 'ECHO': 0.800000011920929, 'HFPC': 0.9166666865348816, 'BBPC': 1.0, 'Whistle': 0.9032257795333862},
AUC: {'Labels_Average': 0.9797139763832092, 'ECHO': 0.9555555582046509, 'HFPC': 0.9932249188423157, 'BBPC': 0.9952632188796997, 'Whistle': 0.9748122096061707},
exact_match: {'Labels_Average': 0.7925925850868225},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  KAM_20200721_17071576.pt  KAM        0.0        0.0    0.000012        0.0
1  KAM_20200722_15000575.pt  KAM        0.0        0.0    0.097758        1.0
2  KAM_20200722_15042061.pt  KAM        0.0        1.0    0.966064        0.0
3  KAM_20200722_15060609.pt  KAM        1.0        1.0    0.999998        0.0
4  KAM_20200722_18350432.pt  KAM        1.0        1.0    0.999945        0.0

   HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0  5.018080e-07        0.0        0.0    0.000002           0.0
1        1.0  9.999906e-01        0.0        0.0    0.000593           1.0
2        0.0  1.534427e-06        0.0        1.0    0.957021           1.0
3        0.0  1.151607e-04        0.0        0.0    0.004165           0.0
4        0.0  2.156915e-03        0.0        0.0    0.011085           1.0

   Whistle_pred  Whistle_probs
0           0.0   4.964350e-07
1           1.0   9.982646e-01
2           1.0   9.991894e-01
3           0.0   4.752073e-01
4           1.0   9.889162e-01
Created test dataloader for site: CAC with 131 samples

Test on site cac Epoch: 0

100%|██████████| 5/5 [00:00<00:00, 11.57it/s]

Test on site cac Epoch: 0 Results -
loss: 24.406,
accuracy: {'Labels_Average': 0.9370229244232178, 'ECHO': 0.9007633328437805, 'HFPC': 0.9312977194786072, 'BBPC': 0.9541984796524048, 'Whistle': 0.9618320465087891},
f1: {'Labels_Average': 0.8301897048950195, 'ECHO': 0.6666666865348816, 'HFPC': 0.7567567825317383, 'BBPC': 0.9318181872367859, 'Whistle': 0.9655172228813171},
precision: {'Labels_Average': 0.8893598914146423, 'ECHO': 0.7647058963775635, 'HFPC': 0.875, 'BBPC': 0.9318181872367859, 'Whistle': 0.98591548204422},
recall: {'Labels_Average': 0.7838349342346191, 'ECHO': 0.5909090638160706, 'HFPC': 0.6666666865348816, 'BBPC': 0.9318181872367859, 'Whistle': 0.9459459185600281},
AUC: {'Labels_Average': 0.9748919010162354, 'ECHO': 0.9341117143630981, 'HFPC': 0.987013041973114, 'BBPC': 0.9822361469268799, 'Whistle': 0.9962067008018494},
exact_match: {'Labels_Average': 0.7862595319747925},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  CAC_20210714_08131200.pt  CAC        0.0        0.0    0.000047        0.0
1  CAC_20210714_08141100.pt  CAC        0.0        0.0    0.000023        0.0
2  CAC_20210714_08184000.pt  CAC        0.0        0.0    0.000284        0.0
3  CAC_20210714_08203400.pt  CAC        0.0        0.0    0.000007        0.0
4  CAC_20210714_08262600.pt  CAC        0.0        0.0    0.000023        0.0

   HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  Whistle_true  \
0        0.0  2.824401e-05        0.0        0.0  2.550021e-05           0.0
1        0.0  5.569861e-06        0.0        0.0  1.172406e-06           0.0
2        0.0  8.804761e-06        0.0        0.0  5.639179e-05           0.0
3        0.0  1.281908e-07        0.0        0.0  1.658769e-07           0.0
4        0.0  1.616482e-07        0.0        0.0  1.330427e-04           0.0

   Whistle_pred  Whistle_probs
0           0.0   1.220176e-02
1           0.0   2.612140e-03
2           0.0   1.082698e-03
3           0.0   1.797753e-07
4           0.0   6.584599e-05
Created test dataloader for site: BSM with 1264 samples

Test on site bsm Epoch: 0

100%|██████████| 40/40 [00:04<00:00,  9.84it/s]

Test on site bsm Epoch: 0 Results -
loss: 3.770,
accuracy: {'Labels_Average': 0.9924842119216919, 'ECHO': 0.9905063509941101, 'HFPC': 0.9912974834442139, 'BBPC': 0.9944620132446289, 'Whistle': 0.9936708807945251},
f1: {'Labels_Average': 0.8849285244941711, 'ECHO': 0.8947368264198303, 'HFPC': 0.8253968358039856, 'BBPC': 0.892307698726654, 'Whistle': 0.9272727370262146},
precision: {'Labels_Average': 0.892875611782074, 'ECHO': 0.8947368264198303, 'HFPC': 0.8965517282485962, 'BBPC': 0.8529411554336548, 'Whistle': 0.9272727370262146},
recall: {'Labels_Average': 0.8805497884750366, 'ECHO': 0.8947368264198303, 'HFPC': 0.7647058963775635, 'BBPC': 0.9354838728904724, 'Whistle': 0.9272727370262146},
AUC: {'Labels_Average': 0.9978962540626526, 'ECHO': 0.9972020387649536, 'HFPC': 0.9977522492408752, 'BBPC': 0.9981948137283325, 'Whistle': 0.998435914516449},
exact_match: {'Labels_Average': 0.9723101258277893},
                   Filename Site  ECHO_true  ECHO_pred    ECHO_probs  \
0  BSM_20170724_10580200.pt  BSM        0.0        0.0  2.896608e-06
1  BSM_20170724_12500200.pt  BSM        0.0        0.0  4.422266e-07
2  BSM_20170724_12560100.pt  BSM        0.0        0.0  6.666681e-06
3  BSM_20170724_13090979.pt  BSM        0.0        0.0  2.534888e-02
4  BSM_20170724_13220150.pt  BSM        0.0        0.0  4.679000e-02

   HFPC_true  HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  \
0        0.0        0.0  3.461628e-08        0.0        0.0  8.896340e-08
1        0.0        0.0  1.570518e-09        0.0        0.0  4.144646e-08
2        0.0        0.0  2.871543e-08        0.0        0.0  1.901450e-05
3        1.0        1.0  9.936199e-01        0.0        0.0  1.287776e-01
4        1.0        1.0  9.695476e-01        0.0        0.0  1.085783e-06

   Whistle_true  Whistle_pred  Whistle_probs
0           0.0           0.0   5.900378e-07
1           0.0           0.0   8.026673e-10
2           0.0           0.0   4.330503e-07
3           1.0           1.0   9.854019e-01
4           0.0           0.0   1.471570e-04
Created test dataloader for site: RDL with 129 samples

Test on site rdl Epoch: 0

100%|██████████| 5/5 [00:00<00:00, 11.60it/s]

Test on site rdl Epoch: 0 Results -
loss: 17.382,
accuracy: {'Labels_Average': 0.9534883499145508, 'ECHO': 0.930232584476471, 'HFPC': 0.9689922332763672, 'BBPC': 0.9379844665527344, 'Whistle': 0.9767441749572754},
f1: {'Labels_Average': 0.897951602935791, 'ECHO': 0.8363636136054993, 'HFPC': 0.9230769276618958, 'BBPC': 0.8620689511299133, 'Whistle': 0.9702970385551453},
precision: {'Labels_Average': 0.8995758295059204, 'ECHO': 0.8518518805503845, 'HFPC': 0.9599999785423279, 'BBPC': 0.8064516186714172, 'Whistle': 0.9800000190734863},
recall: {'Labels_Average': 0.8992569446563721, 'ECHO': 0.8214285969734192, 'HFPC': 0.8888888955116272, 'BBPC': 0.9259259104728699, 'Whistle': 0.9607843160629272},
AUC: {'Labels_Average': 0.9818958044052124, 'ECHO': 0.9653465747833252, 'HFPC': 0.9901960492134094, 'BBPC': 0.9753086566925049, 'Whistle': 0.9967319965362549},
exact_match: {'Labels_Average': 0.8372092843055725},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  RDL_20200722_10411493.pt  RDL        0.0        0.0    0.000005        0.0
1  RDL_20200722_10411593.pt  RDL        0.0        0.0    0.000155        0.0
2  RDL_20200722_10411693.pt  RDL        0.0        0.0    0.000453        0.0
3  RDL_20200722_10421398.pt  RDL        0.0        0.0    0.000010        0.0
4  RDL_20200722_10423086.pt  RDL        0.0        0.0    0.000020        0.0

   HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  Whistle_true  \
0        0.0  2.992546e-08        0.0        0.0  5.650685e-07           0.0
1        0.0  6.508602e-07        0.0        0.0  8.553805e-05           0.0
2        0.0  9.427584e-06        0.0        0.0  1.174048e-05           0.0
3        0.0  7.418118e-11        0.0        0.0  4.504816e-06           0.0
4        0.0  1.273059e-07        0.0        0.0  2.541642e-05           0.0

   Whistle_pred  Whistle_probs
0           0.0   2.185487e-06
1           0.0   3.116757e-04
2           0.0   2.420523e-04
3           0.0   3.093333e-08
4           0.0   1.261932e-05

,Filename,Site,ECHO_true,ECHO_pred,ECHO_probs,HFPC_true,HFPC_pred,HFPC_probs,BBPC_true,BBPC_pred,BBPC_probs,Whistle_true,Whistle_pred,Whistle_probs
0,RDL_20200722_10495100.pt,RDL,0.0,1.0,6.653182e-01,0.0,0.0,2.541073e-07,1.0,1.0,1.000000e+00,1.0,1.0,9.999983e-01
1,RDL_20200722_10530700.pt,RDL,0.0,0.0,1.494951e-06,0.0,0.0,6.434662e-09,1.0,1.0,1.000000e+00,1.0,1.0,9.998509e-01
2,RDL_20200722_10530800.pt,RDL,0.0,0.0,3.102565e-06,0.0,0.0,5.433516e-08,1.0,1.0,9.999998e-01,1.0,1.0,9.999675e-01
3,RDL_20200722_10535400.pt,RDL,0.0,0.0,3.364059e-05,0.0,0.0,2.661448e-06,0.0,0.0,8.817448e-04,0.0,0.0,2.467944e-03
4,RDL_20200722_10560000.pt,RDL,0.0,0.0,4.447617e-01,0.0,0.0,1.353020e-06,1.0,1.0,9.999996e-01,1.0,1.0,9.999981e-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,RDL_20200828_18471143.pt,RDL,1.0,1.0,9.999815e-01,0.0,0.0,2.397118e-04,1.0,1.0,6.450806e-01,1.0,1.0,9.994324e-01
640,RDL_20200828_18482301.pt,RDL,0.0,0.0,2.559880e-02,1.0,1.0,7.016237e-01,1.0,1.0,6.422930e-01,0.0,0.0,1.629033e-01
641,RDL_20200829_13033300.pt,RDL,0.0,0.0,3.636325e-03,0.0,0.0,2.510605e-05,1.0,1.0,5.081753e-01,1.0,1.0,9.971179e-01
642,RDL_20200906_14553196.pt,RDL,0.0,0.0,7.232674e-08,0.0,0.0,9.718217e-11,0.0,0.0,5.850543e-12,0.0,0.0,3.262010e-13
643,RDL_20200906_14573769.pt,RDL,0.0,0.0,8.246334e-05,0.0,0.0,1.236400e-07,0.0,0.0,4.198403e-03,0.0,0.0,2.640057e-04

#### Running all MobileNet variants: layer depth & quantization

In [6]:

n_layers_to_test = [8, 6,  10, 12,]  
# n_layers_to_test = [2, 4, 6, 8, 10, 12,]  
quantization_options = [False,True]

for n_layers in n_layers_to_test:
    for use_quantization in quantization_options:
        # Create run name based on parameters
        quant_suffix = "_qat" if use_quantization else ""
        run_name = f"mobile_net{quant_suffix}_{n_layers}_layers"
        
        print(f"\n{'='*80}")
        print(f"Running experiment: {run_name}")
        print(f"n_layers: {n_layers}, quantization: {use_quantization}")
        print(f"{'='*80}")

        model_class = load_mobilenet_v3_quant if use_quantization else MobileNetMultilabel

        model_kwargs = {
            "pretrained": True,
            "n_layers": n_layers
        }

        if use_quantization:
            model_kwargs["qat"] = True
        
        try:
            run_cross_val(
                labels_df, 
                label_columns, 
                model_class,  
                processed_spects_dir,
                run_name=run_name,
                model_kwargs=model_kwargs, 
                n_splits=5,
                training_config=training_config_default,
                save_models=True,
                use_quantization=use_quantization,
            )
            print(f"✅ Successfully completed: {run_name}")
            
        except Exception as e:
            print(f"❌ Error in experiment {run_name}: {str(e)}")
            print(f"Continuing with next experiment...")
            continue

print(f"\n{'='*80}")
print("All experiments completed!")
print(f"{'='*80}")

Val Epoch: 25

100%|██████████| 78/78 [00:09<00:00,  7.86it/s]

Val Epoch: 25 Results -
loss: 18.293,
accuracy: {'Labels_Average': 0.9726137518882751, 'ECHO': 0.9629480242729187, 'HFPC': 0.9855014085769653, 'BBPC': 0.9810712933540344, 'Whistle': 0.9609343409538269},
f1: {'Labels_Average': 0.8788601756095886, 'ECHO': 0.9471871256828308, 'HFPC': 0.843478262424469, 'BBPC': 0.8303248882293701, 'Whistle': 0.8944504857063293},
precision: {'Labels_Average': 0.8883719444274902, 'ECHO': 0.9482758641242981, 'HFPC': 0.843478262424469, 'BBPC': 0.8778625726699829, 'Whistle': 0.8838709592819214},
recall: {'Labels_Average': 0.8706341981887817, 'ECHO': 0.9461008906364441, 'HFPC': 0.843478262424469, 'BBPC': 0.7876712083816528, 'Whistle': 0.9052863717079163},
AUC: {'Labels_Average': 0.9874508380889893, 'ECHO': 0.9902142286300659, 'HFPC': 0.9879093766212463, 'BBPC': 0.9862003326416016, 'Whistle': 0.9854792356491089},
exact_match: {'Labels_Average': 0.9065646529197693},

Training Epoch: 26

100%|██████████| 311/311 [00:46<00:00,  6.72it/s]

Train Epoch: 26 Results -
loss: 0.456,
accuracy: {'Labels_Average': 0.9988672733306885, 'ECHO': 0.9984897375106812, 'HFPC': 0.9989931583404541, 'BBPC': 0.9997986555099487, 'Whistle': 0.9981876611709595},
f1: {'Labels_Average': 0.9953732490539551, 'ECHO': 0.997732400894165, 'HFPC': 0.990138053894043, 'BBPC': 0.9984301328659058, 'Whistle': 0.995192289352417},
precision: {'Labels_Average': 0.9951527118682861, 'ECHO': 0.9978832602500916, 'HFPC': 0.990138053894043, 'BBPC': 0.9968652129173279, 'Whistle': 0.9957242012023926},
recall: {'Labels_Average': 0.9955951571464539, 'ECHO': 0.9975816011428833, 'HFPC': 0.990138053894043, 'BBPC': 1.0, 'Whistle': 0.9946609735488892},
AUC: {'Labels_Average': 0.9999841451644897, 'ECHO': 0.9999843835830688, 'HFPC': 0.9999895691871643, 'BBPC': 0.9999959468841553, 'Whistle': 0.9999667406082153},
exact_match: {'Labels_Average': 0.9954692125320435},

Val Epoch: 26

100%|██████████| 78/78 [00:09<00:00,  7.82it/s]

Val Epoch: 26 Results -
loss: 17.731,
accuracy: {'Labels_Average': 0.9724124073982239, 'ECHO': 0.9641562700271606, 'HFPC': 0.9838904738426208, 'BBPC': 0.9822794795036316, 'Whistle': 0.9593234062194824},
f1: {'Labels_Average': 0.8768956065177917, 'ECHO': 0.9488799571990967, 'HFPC': 0.8260869383811951, 'BBPC': 0.8439716100692749, 'Whistle': 0.8886438608169556},
precision: {'Labels_Average': 0.8853073716163635, 'ECHO': 0.9505178332328796, 'HFPC': 0.8260869383811951, 'BBPC': 0.875, 'Whistle': 0.8896247148513794},
recall: {'Labels_Average': 0.8690171241760254, 'ECHO': 0.9472476840019226, 'HFPC': 0.8260869383811951, 'BBPC': 0.8150684833526611, 'Whistle': 0.8876652121543884},
AUC: {'Labels_Average': 0.9887259006500244, 'ECHO': 0.9906526803970337, 'HFPC': 0.9917946457862854, 'BBPC': 0.9862120151519775, 'Whistle': 0.9862440824508667},
exact_match: {'Labels_Average': 0.9065646529197693},

Training Epoch: 27

100%|██████████| 311/311 [00:45<00:00,  6.79it/s]

Train Epoch: 27 Results -
loss: 0.328,
accuracy: {'Labels_Average': 0.9992448687553406, 'ECHO': 0.9977849125862122, 'HFPC': 0.9998993277549744, 'BBPC': 0.9997986555099487, 'Whistle': 0.999496579170227},
f1: {'Labels_Average': 0.9981952905654907, 'ECHO': 0.9966737031936646, 'HFPC': 0.9990147948265076, 'BBPC': 0.99842768907547, 'Whistle': 0.998664915561676},
precision: {'Labels_Average': 0.998091459274292, 'ECHO': 0.9969751834869385, 'HFPC': 0.998031497001648, 'BBPC': 0.99842768907547, 'Whistle': 0.9989316463470459},
recall: {'Labels_Average': 0.9982995986938477, 'ECHO': 0.996372401714325, 'HFPC': 1.0, 'BBPC': 0.99842768907547, 'Whistle': 0.9983983039855957},
AUC: {'Labels_Average': 0.9999935626983643, 'ECHO': 0.9999781847000122, 'HFPC': 0.9999996423721313, 'BBPC': 0.999998927116394, 'Whistle': 0.9999975562095642},
exact_match: {'Labels_Average': 0.9969794750213623},

Val Epoch: 27

100%|██████████| 78/78 [00:09<00:00,  7.83it/s]

Val Epoch: 27 Results -
loss: 18.948,
accuracy: {'Labels_Average': 0.970902144908905, 'ECHO': 0.9629480242729187, 'HFPC': 0.9842932224273682, 'BBPC': 0.9798630475997925, 'Whistle': 0.956504225730896},
f1: {'Labels_Average': 0.8689635992050171, 'ECHO': 0.9473081231117249, 'HFPC': 0.8281938433647156, 'BBPC': 0.8214285969734192, 'Whistle': 0.878923773765564},
precision: {'Labels_Average': 0.884674072265625, 'ECHO': 0.9462242722511292, 'HFPC': 0.8392857313156128, 'BBPC': 0.858208954334259, 'Whistle': 0.8949771523475647},
recall: {'Labels_Average': 0.8542232513427734, 'ECHO': 0.9483944773674011, 'HFPC': 0.8173912763595581, 'BBPC': 0.7876712083816528, 'Whistle': 0.8634361028671265},
AUC: {'Labels_Average': 0.988308846950531, 'ECHO': 0.9885780811309814, 'HFPC': 0.9927511215209961, 'BBPC': 0.9866267442703247, 'Whistle': 0.9852794408798218},
exact_match: {'Labels_Average': 0.9009262919425964},
No improvement over last 5 epochs in validation loss. Early stopping...
Training complete. Loading best model weights.
Training complete in 26m 11s

Test Epoch: 0

100%|██████████| 97/97 [00:14<00:00,  6.75it/s]

Test Epoch: 0 Results -
loss: 20.706,
accuracy: {'Labels_Average': 0.9672896862030029, 'ECHO': 0.9497260451316833, 'HFPC': 0.9829197525978088, 'BBPC': 0.9761521220207214, 'Whistle': 0.9603609442710876},
f1: {'Labels_Average': 0.8693623542785645, 'ECHO': 0.9279112815856934, 'HFPC': 0.8427299857139587, 'BBPC': 0.8102564215660095, 'Whistle': 0.8965517282485962},
precision: {'Labels_Average': 0.8830500245094299, 'ECHO': 0.9516587853431702, 'HFPC': 0.8502994179725647, 'BBPC': 0.8404255509376526, 'Whistle': 0.8898163437843323},
recall: {'Labels_Average': 0.8565455675125122, 'ECHO': 0.9053201079368591, 'HFPC': 0.8352941274642944, 'BBPC': 0.7821782231330872, 'Whistle': 0.9033898115158081},
AUC: {'Labels_Average': 0.9847507476806641, 'ECHO': 0.986070990562439, 'HFPC': 0.9843093752861023, 'BBPC': 0.9815239906311035, 'Whistle': 0.9870986342430115},
exact_match: {'Labels_Average': 0.886561393737793},
Final test loss: 20.7057
                   Filename Site  ECHO_true  ECHO_pred    ECHO_probs  \
0  BSM_20170724_09471900.pt  BSM        0.0        0.0  7.741387e-08
1  BSM_20170724_09472400.pt  BSM        0.0        0.0  7.741387e-08
2  BSM_20170724_09472600.pt  BSM        0.0        0.0  7.741387e-08
3  BSM_20170724_09472700.pt  BSM        0.0        0.0  7.741387e-08
4  BSM_20170724_09473100.pt  BSM        0.0        0.0  7.741387e-08

   HFPC_true  HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  \
0        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
1        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
2        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
3        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
4        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08

   Whistle_true  Whistle_pred  Whistle_probs
0           0.0           0.0   7.741387e-08
1           0.0           0.0   7.741387e-08
2           0.0           0.0   7.741387e-08
3           0.0           0.0   7.741387e-08
4           0.0           0.0   7.741387e-08
Size (MB): 4.963302
Size (KB): 4846.974609375

c:\Users\Admin\Desktop\Emmanuel\beluga-call-pipeline\.venv\Lib\site-packages\torch\ao\quantization\utils.py:407: UserWarning: must run observer before calling calculate_qparams. Returning default values.
  warnings.warn(

Test quantization fold 4 Epoch: 0

100%|██████████| 97/97 [00:14<00:00,  6.84it/s]

Test quantization fold 4 Epoch: 0 Results -
loss: 22.980,
accuracy: {'Labels_Average': 0.966725766658783, 'ECHO': 0.9487592577934265, 'HFPC': 0.9832420349121094, 'BBPC': 0.9755075573921204, 'Whistle': 0.9593941569328308},
f1: {'Labels_Average': 0.8685624599456787, 'ECHO': 0.9266943335533142, 'HFPC': 0.8461538553237915, 'BBPC': 0.807106614112854, 'Whistle': 0.8942952752113342},
precision: {'Labels_Average': 0.8782026767730713, 'ECHO': 0.948113203048706, 'HFPC': 0.851190447807312, 'BBPC': 0.828125, 'Whistle': 0.8853820562362671},
recall: {'Labels_Average': 0.8594791889190674, 'ECHO': 0.9062218070030212, 'HFPC': 0.841176450252533, 'BBPC': 0.7871286869049072, 'Whistle': 0.9033898115158081},
AUC: {'Labels_Average': 0.984961211681366, 'ECHO': 0.9865328669548035, 'HFPC': 0.9837769269943237, 'BBPC': 0.9813644886016846, 'Whistle': 0.9881706237792969},
exact_match: {'Labels_Average': 0.8862391114234924},
Size (MB): 1.359426
Size (KB): 1327.564453125
Created test dataloader for site: KAM with 741 samples

Test on site kam Epoch: 0

100%|██████████| 24/24 [00:03<00:00,  7.53it/s]

Test on site kam Epoch: 0 Results -
loss: 26.478,
accuracy: {'Labels_Average': 0.9601889848709106, 'ECHO': 0.9257760047912598, 'HFPC': 0.9824561476707458, 'BBPC': 0.9784075617790222, 'Whistle': 0.9541160464286804},
f1: {'Labels_Average': 0.871314287185669, 'ECHO': 0.9515418410301208, 'HFPC': 0.7936508059501648, 'BBPC': 0.868852436542511, 'Whistle': 0.8712121248245239},
precision: {'Labels_Average': 0.895717203617096, 'ECHO': 0.9747292399406433, 'HFPC': 0.8333333134651184, 'BBPC': 0.8833333253860474, 'Whistle': 0.8914728760719299},
recall: {'Labels_Average': 0.8484245538711548, 'ECHO': 0.9294320344924927, 'HFPC': 0.7575757503509521, 'BBPC': 0.8548387289047241, 'Whistle': 0.8518518805503845},
AUC: {'Labels_Average': 0.9782758355140686, 'ECHO': 0.9658240675926208, 'HFPC': 0.9884651303291321, 'BBPC': 0.9781700372695923, 'Whistle': 0.980644166469574},
exact_match: {'Labels_Average': 0.8515519499778748},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  KAM_20200722_11270553.pt  KAM        1.0        1.0    0.998809        1.0
1  KAM_20200722_15003688.pt  KAM        1.0        0.0    0.218652        1.0
2  KAM_20200722_15024296.pt  KAM        1.0        1.0    0.998809        0.0
3  KAM_20200722_15024496.pt  KAM        1.0        0.0    0.012537        1.0
4  KAM_20200722_15032389.pt  KAM        1.0        0.0    0.000576        0.0

   HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  Whistle_true  \
0        1.0  9.988087e-01        0.0        0.0  7.741387e-08           0.0
1        1.0  9.988087e-01        0.0        0.0  2.178793e-05           1.0
2        0.0  1.052370e-05        0.0        1.0  9.988087e-01           1.0
3        1.0  9.988087e-01        0.0        1.0  8.809313e-01           1.0
4        0.0  3.318359e-07        1.0        1.0  9.988087e-01           1.0

   Whistle_pred  Whistle_probs
0           0.0       0.000045
1           1.0       0.998809
2           1.0       0.998809
3           1.0       0.998809
4           1.0       0.998809

(quantized) test on site kam Epoch: 0

100%|██████████| 24/24 [00:03<00:00,  7.19it/s]

(quantized) test on site kam Epoch: 0 Results -
loss: 26.093,
accuracy: {'Labels_Average': 0.9615384340286255, 'ECHO': 0.9298245906829834, 'HFPC': 0.9838056564331055, 'BBPC': 0.9716598987579346, 'Whistle': 0.9608637094497681},
f1: {'Labels_Average': 0.8689418435096741, 'ECHO': 0.9543058276176453, 'HFPC': 0.800000011920929, 'BBPC': 0.8292682766914368, 'Whistle': 0.8921933174133301},
precision: {'Labels_Average': 0.8988355398178101, 'ECHO': 0.9748653769493103, 'HFPC': 0.8888888955116272, 'BBPC': 0.8360655903816223, 'Whistle': 0.89552241563797},
recall: {'Labels_Average': 0.843334436416626, 'ECHO': 0.93459552526474, 'HFPC': 0.7272727489471436, 'BBPC': 0.8225806355476379, 'Whistle': 0.8888888955116272},
AUC: {'Labels_Average': 0.9793078899383545, 'ECHO': 0.9736983776092529, 'HFPC': 0.9775723218917847, 'BBPC': 0.9804028272628784, 'Whistle': 0.9855579137802124},
exact_match: {'Labels_Average': 0.8542510271072388},
Created test dataloader for site: BSM with 1576 samples

Test on site bsm Epoch: 0

100%|██████████| 50/50 [00:06<00:00,  7.60it/s]

Test on site bsm Epoch: 0 Results -
loss: 7.908,
accuracy: {'Labels_Average': 0.9857233762741089, 'ECHO': 0.971446692943573, 'HFPC': 0.9911167621612549, 'BBPC': 0.9923858046531677, 'Whistle': 0.9879441857337952},
f1: {'Labels_Average': 0.8599709868431091, 'ECHO': 0.8931116461753845, 'HFPC': 0.8793103694915771, 'BBPC': 0.8125, 'Whistle': 0.8549618124961853},
precision: {'Labels_Average': 0.866690993309021, 'ECHO': 0.9170731902122498, 'HFPC': 0.8644067645072937, 'BBPC': 0.8965517282485962, 'Whistle': 0.7887324094772339},
recall: {'Labels_Average': 0.8603243827819824, 'ECHO': 0.8703703880310059, 'HFPC': 0.8947368264198303, 'BBPC': 0.7428571581840515, 'Whistle': 0.9333333373069763},
AUC: {'Labels_Average': 0.990902841091156, 'ECHO': 0.9934419393539429, 'HFPC': 0.9876881837844849, 'BBPC': 0.9960971474647522, 'Whistle': 0.9863840341567993},
exact_match: {'Labels_Average': 0.9498730897903442},
                   Filename Site  ECHO_true  ECHO_pred    ECHO_probs  \
0  BSM_20170724_09471900.pt  BSM        0.0        0.0  7.741387e-08
1  BSM_20170724_09472400.pt  BSM        0.0        0.0  7.741387e-08
2  BSM_20170724_09472600.pt  BSM        0.0        0.0  7.741387e-08
3  BSM_20170724_09472700.pt  BSM        0.0        0.0  7.741387e-08
4  BSM_20170724_09473100.pt  BSM        0.0        0.0  7.741387e-08

   HFPC_true  HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  \
0        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
1        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
2        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
3        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
4        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08

   Whistle_true  Whistle_pred  Whistle_probs
0           0.0           0.0   7.741387e-08
1           0.0           0.0   7.741387e-08
2           0.0           0.0   7.741387e-08
3           0.0           0.0   7.741387e-08
4           0.0           0.0   7.741387e-08

(quantized) test on site bsm Epoch: 0

100%|██████████| 50/50 [00:07<00:00,  7.05it/s]

(quantized) test on site bsm Epoch: 0 Results -
loss: 10.061,
accuracy: {'Labels_Average': 0.9852474927902222, 'ECHO': 0.970812201499939, 'HFPC': 0.9917512536048889, 'BBPC': 0.9923858046531677, 'Whistle': 0.9860405921936035},
f1: {'Labels_Average': 0.857646644115448, 'ECHO': 0.8915094137191772, 'HFPC': 0.8907563090324402, 'BBPC': 0.8125, 'Whistle': 0.8358209133148193},
precision: {'Labels_Average': 0.8542002439498901, 'ECHO': 0.9086538553237915, 'HFPC': 0.8548387289047241, 'BBPC': 0.8965517282485962, 'Whistle': 0.7567567825317383},
recall: {'Labels_Average': 0.8702538013458252, 'ECHO': 0.875, 'HFPC': 0.9298245906829834, 'BBPC': 0.7428571581840515, 'Whistle': 0.9333333373069763},
AUC: {'Labels_Average': 0.992483913898468, 'ECHO': 0.9925705194473267, 'HFPC': 0.9970952868461609, 'BBPC': 0.9942430853843689, 'Whistle': 0.9860267639160156},
exact_match: {'Labels_Average': 0.950507640838623},
Created test dataloader for site: RDL with 129 samples

Test on site rdl Epoch: 0

100%|██████████| 5/5 [00:00<00:00,  7.20it/s]

Test on site rdl Epoch: 0 Results -
loss: 43.000,
accuracy: {'Labels_Average': 0.9186046123504639, 'ECHO': 0.9069767594337463, 'HFPC': 0.9379844665527344, 'BBPC': 0.8837209343910217, 'Whistle': 0.9457364082336426},
f1: {'Labels_Average': 0.8608408570289612, 'ECHO': 0.8636363744735718, 'HFPC': 0.8947368264198303, 'BBPC': 0.7368420958518982, 'Whistle': 0.9481481313705444},
precision: {'Labels_Average': 0.8684290647506714, 'ECHO': 0.9047619104385376, 'HFPC': 0.8500000238418579, 'BBPC': 0.7777777910232544, 'Whistle': 0.9411764740943909},
recall: {'Labels_Average': 0.8564388155937195, 'ECHO': 0.8260869383811951, 'HFPC': 0.9444444179534912, 'BBPC': 0.699999988079071, 'Whistle': 0.9552238583564758},
AUC: {'Labels_Average': 0.9631149172782898, 'ECHO': 0.953902542591095, 'HFPC': 0.9646058082580566, 'BBPC': 0.9663299918174744, 'Whistle': 0.9676214456558228},
exact_match: {'Labels_Average': 0.7364341020584106},
                   Filename Site  ECHO_true  ECHO_pred    ECHO_probs  \
0  RDL_20200722_10425555.pt  RDL        0.0        1.0  9.988087e-01
1  RDL_20200723_14300900.pt  RDL        0.0        0.0  7.741387e-08
2  RDL_20200723_14305033.pt  RDL        0.0        0.0  7.741387e-08
3  RDL_20200723_14305575.pt  RDL        0.0        0.0  2.144420e-02
4  RDL_20200723_14332400.pt  RDL        0.0        0.0  8.241173e-07

   HFPC_true  HFPC_pred    HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  \
0        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
1        0.0        0.0  7.741387e-08        0.0        0.0  5.727472e-07
2        0.0        0.0  7.741387e-08        0.0        0.0  7.741387e-08
3        0.0        0.0  7.741387e-08        0.0        0.0  2.046699e-06
4        0.0        0.0  5.727472e-07        1.0        1.0  9.988087e-01

   Whistle_true  Whistle_pred  Whistle_probs
0           0.0           0.0   2.944962e-06
1           0.0           0.0   5.757204e-04
2           0.0           0.0   7.741387e-08
3           0.0           0.0   2.463178e-03
4           1.0           1.0   9.988087e-01

(quantized) test on site rdl Epoch: 0

100%|██████████| 5/5 [00:00<00:00,  8.18it/s]

(quantized) test on site rdl Epoch: 0 Results -
loss: 51.184,
accuracy: {'Labels_Average': 0.9166666865348816, 'ECHO': 0.9069767594337463, 'HFPC': 0.930232584476471, 'BBPC': 0.8914728760719299, 'Whistle': 0.9379844665527344},
f1: {'Labels_Average': 0.862175703048706, 'ECHO': 0.8666666746139526, 'HFPC': 0.8831169009208679, 'BBPC': 0.7586206793785095, 'Whistle': 0.9402984976768494},
precision: {'Labels_Average': 0.8604111671447754, 'ECHO': 0.8863636255264282, 'HFPC': 0.8292682766914368, 'BBPC': 0.7857142686843872, 'Whistle': 0.9402984976768494},
recall: {'Labels_Average': 0.8664755821228027, 'ECHO': 0.8478260636329651, 'HFPC': 0.9444444179534912, 'BBPC': 0.7333333492279053, 'Whistle': 0.9402984976768494},
AUC: {'Labels_Average': 0.9691227674484253, 'ECHO': 0.9566526412963867, 'HFPC': 0.9734169840812683, 'BBPC': 0.9661616086959839, 'Whistle': 0.9802598357200623},
exact_match: {'Labels_Average': 0.7441860437393188},
Created test dataloader for site: CAC with 657 samples

Test on site cac Epoch: 0

100%|██████████| 21/21 [00:02<00:00,  7.92it/s]

Test on site cac Epoch: 0 Results -
loss: 36.316,
accuracy: {'Labels_Average': 0.9406392574310303, 'ECHO': 0.9330289363861084, 'HFPC': 0.9726027250289917, 'BBPC': 0.95281583070755, 'Whistle': 0.9041095972061157},
f1: {'Labels_Average': 0.8473471403121948, 'ECHO': 0.9153845906257629, 'HFPC': 0.7804877758026123, 'BBPC': 0.7891156673431396, 'Whistle': 0.9044005870819092},
precision: {'Labels_Average': 0.8712427020072937, 'ECHO': 0.9370078444480896, 'HFPC': 0.8421052694320679, 'BBPC': 0.8055555820465088, 'Whistle': 0.9003021121025085},
recall: {'Labels_Average': 0.8259698748588562, 'ECHO': 0.8947368264198303, 'HFPC': 0.7272727489471436, 'BBPC': 0.7733333110809326, 'Whistle': 0.9085366129875183},
AUC: {'Labels_Average': 0.9623892307281494, 'ECHO': 0.971083402633667, 'HFPC': 0.9613674283027649, 'BBPC': 0.9525887370109558, 'Whistle': 0.96451735496521},
exact_match: {'Labels_Average': 0.8036529421806335},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  CAC_20210714_08002100.pt  CAC        1.0        1.0    0.998809        0.0
1  CAC_20210714_08002300.pt  CAC        1.0        1.0    0.998809        0.0
2  CAC_20210714_08003100.pt  CAC        1.0        1.0    0.998809        0.0
3  CAC_20210714_08003200.pt  CAC        1.0        1.0    0.998809        0.0
4  CAC_20210714_08003800.pt  CAC        1.0        1.0    0.998809        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0    0.000400        0.0        0.0    0.000004           1.0
1        0.0    0.000002        0.0        0.0    0.000006           1.0
2        0.0    0.000001        0.0        0.0    0.012537           1.0
3        0.0    0.000004        0.0        0.0    0.002463           0.0
4        0.0    0.000400        0.0        0.0    0.002463           1.0

   Whistle_pred  Whistle_probs
0           1.0       0.998809
1           1.0       0.998809
2           1.0       0.998809
3           1.0       0.880931
4           1.0       0.633161

(quantized) test on site cac Epoch: 0

100%|██████████| 21/21 [00:02<00:00,  7.19it/s]

(quantized) test on site cac Epoch: 0 Results -
loss: 40.183,
accuracy: {'Labels_Average': 0.9379755854606628, 'ECHO': 0.9254185557365417, 'HFPC': 0.9726027250289917, 'BBPC': 0.9558599591255188, 'Whistle': 0.8980212807655334},
f1: {'Labels_Average': 0.8471972942352295, 'ECHO': 0.9052224159240723, 'HFPC': 0.7804877758026123, 'BBPC': 0.8053691387176514, 'Whistle': 0.8977099061012268},
precision: {'Labels_Average': 0.8710674047470093, 'ECHO': 0.9322709441184998, 'HFPC': 0.8421052694320679, 'BBPC': 0.8108108043670654, 'Whistle': 0.8990825414657593},
recall: {'Labels_Average': 0.8258283138275146, 'ECHO': 0.8796992301940918, 'HFPC': 0.7272727489471436, 'BBPC': 0.800000011920929, 'Whistle': 0.8963414430618286},
AUC: {'Labels_Average': 0.9596536159515381, 'ECHO': 0.9710882306098938, 'HFPC': 0.9504486918449402, 'BBPC': 0.9534821510314941, 'Whistle': 0.9635953903198242},
exact_match: {'Labels_Average': 0.7960426211357117},
✅ Successfully completed: mobile_net_qat_12_layers

================================================================================
All experiments completed!
================================================================================

<h4>Function call template to run quick experiments<h4>

In [ ]:
run_cross_val(
    labels_df, 
    label_columns, 
    MobileNetMultilabel,  
    processed_spects_dir,
    run_name="mobile_net_hp_1024_8_layers_all_absences",
    model_kwargs={
        "pretrained":True,
        "n_layers": 8
    }, 
    n_splits=5,
    training_config=training_config_default,
    save_models=True,
    use_quantization=False,
)

## Site Generalization Experiments


1. **Site-specific models** — train a separate model per site.
2. **Leave-One-Site-Out** — train on all but one site and test on the held-out site to assess generalizability.

All runs follow the protocol described in the paper.

In [20]:
from training.cross_validation import create_test_fold_indices
from sklearn.model_selection import KFold, train_test_split
from models.utils import aggregate_folds_testing_metrics



labels_df = pd.read_csv("../data/Verified_Dataset/labels/labels_merged.csv")
labels_df["ClipFilenamePt"] = labels_df["clip_filename"].str.replace(".wav", ".pt", regex=False)


label_columns = ["ECHO", "HFPC", "BBPC", "Whistle"]

data_dir = "../data"
processed_spects_dir = data_dir + "/Verified_Dataset/spectrograms/"

results_dir = "./results/new_dataset"
# labels_df =labels_df[labels_df["labeling_effort"].isin([ "irene_20min", "irene_5min"])]
# labels_df =labels_df[labels_df["labeling_effort"].isin(["old_abs_from_3s_snippets", "old_abs_CAC_last_samples", "irene_20min", "irene_5min"])]
labels_df =labels_df[labels_df["Site"] != "BSM"]
labels_df.reset_index(drop=True, inplace=True)

labels_df = create_test_fold_indices(labels_df, 5)

In [22]:
labels_df["Call"].value_counts()

Call
1    5475
0    2161
Name: count, dtype: int64

In [8]:
labels_df.columns

Index(['clip_filename', 'ECHO', 'BBPC', 'HFPC', 'Whistle', 'Call', 'Boat',
       'labeling_effort', 'DETAIL', 'Begin Time (s)', 'End Time (s)',
       'GROUNDTRUTH', 'Notes', 'original_filename', 'labeled_snippet_filename',
       'snippet_start_time', 'snippet_start_s', 'snippet_end_s', 'Site',
       'labeled_snippet_dir', 'HydrophoneModel', 'HydrophoneSensitivity',
       'clip_start_time', 'clip_end_time', 'DETAILS', 'boat_labeling_file',
       'boat_labeling_file_id', 'annotator', 'SnippetFilename', 'start_s',
       'end_s', 'ClipFilenamePt'],
      dtype='str')

### Site-specific models

In [13]:
all_sites = ["RDL", "CAC", "BSM", "KAM" ]

use_quantization = False

for train_site in all_sites:

    for fold_idx in range(5):
        
        model_class = load_mobilenet_v3_quant if use_quantization else MobileNetMultilabel

        model = model_class(
            pretrained=True,
            n_layers=8,
            num_classes=len(label_columns)
        )

        train_site_df = labels_df[labels_df["Site"]==train_site]
        train_data = train_site_df[train_site_df["test_fold_idx"] != fold_idx]
        train_data, val_data = train_test_split(train_data, test_size=0.2, random_state=42, stratify=train_data['Site'])
        
        test_data = train_site_df[train_site_df["test_fold_idx"] == fold_idx]

        run_name = f"{train_site}_only"
        if use_quantization:
            run_name = run_name + "_qat"


        run_dir, _, _ = train_model(
            labels_df,
            label_columns,
            model,
            train_data,
            val_data,
            test_data,
            processed_spects_dir=processed_spects_dir,
            fold_idx=fold_idx,
            results_dir="./results/sites_generalization_no_boat",
            run_name=run_name,
            training_config=training_config_default,
            use_quantization=use_quantization,
            compute_sites_metrics=True
        )

    aggregate_folds_testing_metrics(run_dir)

Val Epoch: 40

100%|██████████| 8/8 [00:00<00:00, 12.46it/s]

Val Epoch: 40 Results -
loss: 22.455,
accuracy: {'Labels_Average': 0.9597457647323608, 'ECHO': 0.9788135886192322, 'HFPC': 0.9788135886192322, 'BBPC': 0.9661017060279846, 'Whistle': 0.9152542352676392},
f1: {'Labels_Average': 0.8806450366973877, 'ECHO': 0.9854227304458618, 'HFPC': 0.761904776096344, 'BBPC': 0.8888888955116272, 'Whistle': 0.8863636255264282},
precision: {'Labels_Average': 0.9094022512435913, 'ECHO': 0.9768785834312439, 'HFPC': 0.8888888955116272, 'BBPC': 0.8648648858070374, 'Whistle': 0.9069767594337463},
recall: {'Labels_Average': 0.8604341745376587, 'ECHO': 0.9941176176071167, 'HFPC': 0.6666666865348816, 'BBPC': 0.9142857193946838, 'Whistle': 0.8666666746139526},
AUC: {'Labels_Average': 0.9536234140396118, 'ECHO': 0.9959001541137695, 'HFPC': 0.8623511791229248, 'BBPC': 0.9945985078811646, 'Whistle': 0.9616438746452332},
exact_match: {'Labels_Average': 0.8516949415206909},

Training Epoch: 41

100%|██████████| 30/30 [00:03<00:00,  9.68it/s]

Train Epoch: 41 Results -
loss: 0.486,
accuracy: {'Labels_Average': 0.9989373087882996, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 0.9989373087882996, 'Whistle': 0.9968119263648987},
f1: {'Labels_Average': 0.9979671835899353, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 0.9961977005004883, 'Whistle': 0.9956709742546082},
precision: {'Labels_Average': 0.9985590577125549, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9942362904548645},
recall: {'Labels_Average': 0.9973835349082947, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 0.9924242496490479, 'Whistle': 0.9971098303794861},
AUC: {'Labels_Average': 0.9999915361404419, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.999966025352478},
exact_match: {'Labels_Average': 0.9957491755485535},

Val Epoch: 41

100%|██████████| 8/8 [00:00<00:00, 12.05it/s]

Val Epoch: 41 Results -
loss: 23.813,
accuracy: {'Labels_Average': 0.9586864709854126, 'ECHO': 0.9788135886192322, 'HFPC': 0.9745762944221497, 'BBPC': 0.9661017060279846, 'Whistle': 0.9152542352676392},
f1: {'Labels_Average': 0.8706722259521484, 'ECHO': 0.9854227304458618, 'HFPC': 0.7272727489471436, 'BBPC': 0.8823529481887817, 'Whistle': 0.8876404762268066},
precision: {'Labels_Average': 0.8959242105484009, 'ECHO': 0.9768785834312439, 'HFPC': 0.800000011920929, 'BBPC': 0.9090909361839294, 'Whistle': 0.8977272510528564},
recall: {'Labels_Average': 0.8489261865615845, 'ECHO': 0.9941176176071167, 'HFPC': 0.6666666865348816, 'BBPC': 0.8571428656578064, 'Whistle': 0.8777777552604675},
AUC: {'Labels_Average': 0.9540085792541504, 'ECHO': 0.9946523904800415, 'HFPC': 0.8701636791229248, 'BBPC': 0.9924662113189697, 'Whistle': 0.9587518572807312},
exact_match: {'Labels_Average': 0.8559321761131287},

Training Epoch: 42

100%|██████████| 30/30 [00:03<00:00,  9.54it/s]

Train Epoch: 42 Results -
loss: 0.415,
accuracy: {'Labels_Average': 0.9989373087882996, 'ECHO': 0.9989373087882996, 'HFPC': 0.9989373087882996, 'BBPC': 1.0, 'Whistle': 0.9978746175765991},
f1: {'Labels_Average': 0.997144341468811, 'ECHO': 0.9992278218269348, 'HFPC': 0.9922480583190918, 'BBPC': 1.0, 'Whistle': 0.9971014261245728},
precision: {'Labels_Average': 0.9996141791343689, 'ECHO': 0.9984567761421204, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 1.0},
recall: {'Labels_Average': 0.994708776473999, 'ECHO': 1.0, 'HFPC': 0.9846153855323792, 'BBPC': 1.0, 'Whistle': 0.9942196607589722},
AUC: {'Labels_Average': 0.9999988079071045, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9999951124191284},
exact_match: {'Labels_Average': 0.9957491755485535},

Val Epoch: 42

100%|██████████| 8/8 [00:00<00:00, 11.96it/s]

Val Epoch: 42 Results -
loss: 24.044,
accuracy: {'Labels_Average': 0.9586864709854126, 'ECHO': 0.9703390002250671, 'HFPC': 0.9788135886192322, 'BBPC': 0.9661017060279846, 'Whistle': 0.9194915294647217},
f1: {'Labels_Average': 0.8842723369598389, 'ECHO': 0.9794721603393555, 'HFPC': 0.782608687877655, 'BBPC': 0.8823529481887817, 'Whistle': 0.8926553726196289},
precision: {'Labels_Average': 0.9029817581176758, 'ECHO': 0.9766082167625427, 'HFPC': 0.8181818127632141, 'BBPC': 0.9090909361839294, 'Whistle': 0.9080459475517273},
recall: {'Labels_Average': 0.8668184280395508, 'ECHO': 0.9823529124259949, 'HFPC': 0.75, 'BBPC': 0.8571428656578064, 'Whistle': 0.8777777552604675},
AUC: {'Labels_Average': 0.9573062658309937, 'ECHO': 0.9956328272819519, 'HFPC': 0.8820684552192688, 'BBPC': 0.9945985078811646, 'Whistle': 0.9569253921508789},
exact_match: {'Labels_Average': 0.8559321761131287},

Training Epoch: 43

100%|██████████| 30/30 [00:03<00:00,  9.51it/s]

Train Epoch: 43 Results -
loss: 0.388,
accuracy: {'Labels_Average': 0.9994686841964722, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9978746175765991},
f1: {'Labels_Average': 0.9992774724960327, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9971098303794861},
precision: {'Labels_Average': 0.9992774724960327, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9971098303794861},
recall: {'Labels_Average': 0.9992774724960327, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9971098303794861},
AUC: {'Labels_Average': 0.9999951124191284, 'ECHO': 1.0, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9999805688858032},
exact_match: {'Labels_Average': 0.9978746175765991},

Val Epoch: 43

100%|██████████| 8/8 [00:00<00:00, 12.07it/s]

Val Epoch: 43 Results -
loss: 23.853,
accuracy: {'Labels_Average': 0.9597457647323608, 'ECHO': 0.9745762944221497, 'HFPC': 0.9745762944221497, 'BBPC': 0.9703390002250671, 'Whistle': 0.9194915294647217},
f1: {'Labels_Average': 0.8744766712188721, 'ECHO': 0.9824561476707458, 'HFPC': 0.7272727489471436, 'BBPC': 0.89552241563797, 'Whistle': 0.8926553726196289},
precision: {'Labels_Average': 0.9055725336074829, 'ECHO': 0.9767441749572754, 'HFPC': 0.800000011920929, 'BBPC': 0.9375, 'Whistle': 0.9080459475517273},
recall: {'Labels_Average': 0.847455620765686, 'ECHO': 0.9882352948188782, 'HFPC': 0.6666666865348816, 'BBPC': 0.8571428656578064, 'Whistle': 0.8777777552604675},
AUC: {'Labels_Average': 0.9560035467147827, 'ECHO': 0.9961675405502319, 'HFPC': 0.875744104385376, 'BBPC': 0.9950249195098877, 'Whistle': 0.9570776224136353},
exact_match: {'Labels_Average': 0.8601694703102112},

Training Epoch: 44

100%|██████████| 30/30 [00:03<00:00,  9.66it/s]

Train Epoch: 44 Results -
loss: 0.360,
accuracy: {'Labels_Average': 0.9992029666900635, 'ECHO': 0.9978746175765991, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9989373087882996},
f1: {'Labels_Average': 0.9992527961730957, 'ECHO': 0.9984543919563293, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9985569715499878},
precision: {'Labels_Average': 0.998893141746521, 'ECHO': 0.9984543919563293, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 0.9971181750297546},
recall: {'Labels_Average': 0.9996135830879211, 'ECHO': 0.9984543919563293, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 1.0},
AUC: {'Labels_Average': 0.9999986886978149, 'ECHO': 0.9999947547912598, 'HFPC': 1.0, 'BBPC': 1.0, 'Whistle': 1.0},
exact_match: {'Labels_Average': 0.9968119263648987},

Val Epoch: 44

100%|██████████| 8/8 [00:00<00:00, 12.04it/s]

Val Epoch: 44 Results -
loss: 23.602,
accuracy: {'Labels_Average': 0.9576271772384644, 'ECHO': 0.9618644118309021, 'HFPC': 0.9788135886192322, 'BBPC': 0.9703390002250671, 'Whistle': 0.9194915294647217},
f1: {'Labels_Average': 0.8817179799079895, 'ECHO': 0.9737609624862671, 'HFPC': 0.761904776096344, 'BBPC': 0.8985507488250732, 'Whistle': 0.8926553726196289},
precision: {'Labels_Average': 0.9185043573379517, 'ECHO': 0.9653179049491882, 'HFPC': 0.8888888955116272, 'BBPC': 0.9117646813392639, 'Whistle': 0.9080459475517273},
recall: {'Labels_Average': 0.8531279563903809, 'ECHO': 0.9823529124259949, 'HFPC': 0.6666666865348816, 'BBPC': 0.8857142925262451, 'Whistle': 0.8777777552604675},
AUC: {'Labels_Average': 0.9583185315132141, 'ECHO': 0.9961675405502319, 'HFPC': 0.8839285373687744, 'BBPC': 0.9948827624320984, 'Whistle': 0.9582952857017517},
exact_match: {'Labels_Average': 0.8516949415206909},
No improvement over last 5 epochs in validation loss. Early stopping...
Training complete. Loading best model weights.
Training complete in 2m 53s

Test Epoch: 0

100%|██████████| 10/10 [00:00<00:00, 10.38it/s]

Test Epoch: 0 Results -
loss: 26.498,
accuracy: {'Labels_Average': 0.9523809552192688, 'ECHO': 0.9625850319862366, 'HFPC': 0.976190447807312, 'BBPC': 0.9523809552192688, 'Whistle': 0.918367326259613},
f1: {'Labels_Average': 0.8822202682495117, 'ECHO': 0.9739952683448792, 'HFPC': 0.8108108043670654, 'BBPC': 0.8541666865348816, 'Whistle': 0.8899082541465759},
precision: {'Labels_Average': 0.9043906927108765, 'ECHO': 0.9493087530136108, 'HFPC': 0.8333333134651184, 'BBPC': 0.9111111164093018, 'Whistle': 0.9238095283508301},
recall: {'Labels_Average': 0.8629506230354309, 'ECHO': 1.0, 'HFPC': 0.7894737124443054, 'BBPC': 0.8039215803146362, 'Whistle': 0.8584070801734924},
AUC: {'Labels_Average': 0.9696357250213623, 'ECHO': 0.9938217401504517, 'HFPC': 0.95885169506073, 'BBPC': 0.9580408334732056, 'Whistle': 0.9678286910057068},
exact_match: {'Labels_Average': 0.8265306353569031},
Final test loss: 26.4975
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  KAM_20200722_11270653.pt  KAM        1.0        1.0    0.999909        0.0
1  KAM_20200722_15000675.pt  KAM        0.0        1.0    0.527717        1.0
2  KAM_20200722_15003488.pt  KAM        1.0        1.0    0.998641        0.0
3  KAM_20200722_15003588.pt  KAM        1.0        1.0    0.843444        1.0
4  KAM_20200722_15024396.pt  KAM        0.0        1.0    0.995521        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0    0.000890        0.0        0.0    0.000291           0.0
1        1.0    0.999626        1.0        0.0    0.022384           1.0
2        0.0    0.003651        1.0        0.0    0.280844           1.0
3        1.0    0.999511        0.0        0.0    0.001077           1.0
4        0.0    0.003826        0.0        1.0    0.703620           1.0

   Whistle_pred  Whistle_probs
0           0.0       0.000004
1           1.0       0.999623
2           1.0       0.993374
3           1.0       0.999547
4           1.0       0.999912
Size (MB): 0.886346
Size (KB): 865.572265625
Created test dataloader for site: KAM with 294 samples

Test on site kam Epoch: 0

100%|██████████| 10/10 [00:00<00:00, 10.49it/s]

Test on site kam Epoch: 0 Results -
loss: 26.498,
accuracy: {'Labels_Average': 0.9523809552192688, 'ECHO': 0.9625850319862366, 'HFPC': 0.976190447807312, 'BBPC': 0.9523809552192688, 'Whistle': 0.918367326259613},
f1: {'Labels_Average': 0.8822202682495117, 'ECHO': 0.9739952683448792, 'HFPC': 0.8108108043670654, 'BBPC': 0.8541666865348816, 'Whistle': 0.8899082541465759},
precision: {'Labels_Average': 0.9043906927108765, 'ECHO': 0.9493087530136108, 'HFPC': 0.8333333134651184, 'BBPC': 0.9111111164093018, 'Whistle': 0.9238095283508301},
recall: {'Labels_Average': 0.8629506230354309, 'ECHO': 1.0, 'HFPC': 0.7894737124443054, 'BBPC': 0.8039215803146362, 'Whistle': 0.8584070801734924},
AUC: {'Labels_Average': 0.9696357250213623, 'ECHO': 0.9938217401504517, 'HFPC': 0.95885169506073, 'BBPC': 0.9580408334732056, 'Whistle': 0.9678286910057068},
exact_match: {'Labels_Average': 0.8265306353569031},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  KAM_20200722_11270653.pt  KAM        1.0        1.0    0.999909        0.0
1  KAM_20200722_15000675.pt  KAM        0.0        1.0    0.527717        1.0
2  KAM_20200722_15003488.pt  KAM        1.0        1.0    0.998641        0.0
3  KAM_20200722_15003588.pt  KAM        1.0        1.0    0.843444        1.0
4  KAM_20200722_15024396.pt  KAM        0.0        1.0    0.995521        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0    0.000890        0.0        0.0    0.000291           0.0
1        1.0    0.999626        1.0        0.0    0.022384           1.0
2        0.0    0.003651        1.0        0.0    0.280844           1.0
3        1.0    0.999511        0.0        0.0    0.001077           1.0
4        0.0    0.003826        0.0        1.0    0.703620           1.0

   Whistle_pred  Whistle_probs
0           0.0       0.000004
1           1.0       0.999623
2           1.0       0.993374
3           1.0       0.999547
4           1.0       0.999912
Created test dataloader for site: RDL with 123 samples

Test on site rdl Epoch: 0

100%|██████████| 4/4 [00:00<00:00, 10.59it/s]

Test on site rdl Epoch: 0 Results -
loss: 54.142,
accuracy: {'Labels_Average': 0.8841463327407837, 'ECHO': 0.707317054271698, 'HFPC': 0.9674796462059021, 'BBPC': 0.9024389982223511, 'Whistle': 0.9593495726585388},
f1: {'Labels_Average': 0.8175476789474487, 'ECHO': 0.5909090638160706, 'HFPC': 0.8999999761581421, 'BBPC': 0.8235294222831726, 'Whistle': 0.9557521939277649},
precision: {'Labels_Average': 0.7498221397399902, 'ECHO': 0.4333333373069763, 'HFPC': 0.8571428656578064, 'BBPC': 0.7777777910232544, 'Whistle': 0.931034505367279},
recall: {'Labels_Average': 0.9331895112991333, 'ECHO': 0.9285714030265808, 'HFPC': 0.9473684430122375, 'BBPC': 0.875, 'Whistle': 0.9818181991577148},
AUC: {'Labels_Average': 0.9533776640892029, 'ECHO': 0.8774435520172119, 'HFPC': 0.9984817504882812, 'BBPC': 0.9469436407089233, 'Whistle': 0.990641713142395},
exact_match: {'Labels_Average': 0.5853658318519592},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  RDL_20200722_10411493.pt  RDL        0.0        0.0    0.190917        0.0
1  RDL_20200722_10422986.pt  RDL        0.0        0.0    0.498866        0.0
2  RDL_20200722_10423086.pt  RDL        0.0        0.0    0.118650        0.0
3  RDL_20200722_10454127.pt  RDL        0.0        0.0    0.391195        0.0
4  RDL_20200722_10495200.pt  RDL        0.0        1.0    0.978792        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0    0.002038        0.0        0.0    0.000847           0.0
1        0.0    0.000279        0.0        0.0    0.000179           0.0
2        0.0    0.003465        0.0        0.0    0.011064           0.0
3        0.0    0.000871        0.0        0.0    0.000111           0.0
4        0.0    0.001069        1.0        1.0    0.998586           1.0

   Whistle_pred  Whistle_probs
0           0.0       0.000431
1           0.0       0.000003
2           0.0       0.000839
3           0.0       0.000036
4           1.0       0.889735
Created test dataloader for site: CAC with 437 samples

Test on site cac Epoch: 0

100%|██████████| 14/14 [00:01<00:00,  9.98it/s]

Test on site cac Epoch: 0 Results -
loss: 57.053,
accuracy: {'Labels_Average': 0.8987414240837097, 'ECHO': 0.9038901329040527, 'HFPC': 0.9656750559806824, 'BBPC': 0.8993135094642639, 'Whistle': 0.8260869383811951},
f1: {'Labels_Average': 0.7573743462562561, 'ECHO': 0.8703703880310059, 'HFPC': 0.6666666865348816, 'BBPC': 0.6507936716079712, 'Whistle': 0.8416666388511658},
precision: {'Labels_Average': 0.8437986969947815, 'ECHO': 0.892405092716217, 'HFPC': 0.9375, 'BBPC': 0.5694444179534912, 'Whistle': 0.9758453965187073},
recall: {'Labels_Average': 0.7164562344551086, 'ECHO': 0.849397599697113, 'HFPC': 0.517241358757019, 'BBPC': 0.7592592835426331, 'Whistle': 0.7399267554283142},
AUC: {'Labels_Average': 0.9282768964767456, 'ECHO': 0.963144063949585, 'HFPC': 0.9023833870887756, 'BBPC': 0.9201478958129883, 'Whistle': 0.9274322986602783},
exact_match: {'Labels_Average': 0.6453089118003845},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  CAC_20210714_08002100.pt  CAC        1.0        1.0    0.999998        0.0
1  CAC_20210714_08002400.pt  CAC        1.0        1.0    0.999997        0.0
2  CAC_20210714_08002500.pt  CAC        1.0        1.0    1.000000        0.0
3  CAC_20210714_08002600.pt  CAC        1.0        1.0    0.999999        0.0
4  CAC_20210714_08002800.pt  CAC        1.0        1.0    1.000000        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0    0.000032        0.0        0.0    0.048202           1.0
1        0.0    0.000090        0.0        0.0    0.000033           0.0
2        0.0    0.000124        0.0        0.0    0.000021           1.0
3        0.0    0.334200        0.0        0.0    0.000041           1.0
4        0.0    0.001885        0.0        0.0    0.000195           1.0

   Whistle_pred  Whistle_probs
0           1.0       0.999960
1           0.0       0.000001
2           0.0       0.360045
3           1.0       0.999699
4           1.0       0.999731
Created test dataloader for site: BSM with 1378 samples

Test on site bsm Epoch: 0

100%|██████████| 44/44 [00:04<00:00, 10.07it/s]

Test on site bsm Epoch: 0 Results -
loss: 23.437,
accuracy: {'Labels_Average': 0.9517416954040527, 'ECHO': 0.958635687828064, 'HFPC': 0.9477503895759583, 'BBPC': 0.9600870609283447, 'Whistle': 0.9404934644699097},
f1: {'Labels_Average': 0.6215034127235413, 'ECHO': 0.8308605551719666, 'HFPC': 0.5324675440788269, 'BBPC': 0.4954128563404083, 'Whistle': 0.6272727251052856},
precision: {'Labels_Average': 0.4951186180114746, 'ECHO': 0.7216494679450989, 'HFPC': 0.40594059228897095, 'BBPC': 0.3802816867828369, 'Whistle': 0.4726027250289917},
recall: {'Labels_Average': 0.8488911390304565, 'ECHO': 0.9790209531784058, 'HFPC': 0.7735849022865295, 'BBPC': 0.7105262875556946, 'Whistle': 0.9324324131011963},
AUC: {'Labels_Average': 0.9732560515403748, 'ECHO': 0.994269609451294, 'HFPC': 0.9560270309448242, 'BBPC': 0.958375871181488, 'Whistle': 0.9843516945838928},
exact_match: {'Labels_Average': 0.8613933324813843},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  BSM_20170724_10580200.pt  BSM        0.0        0.0    0.001890        0.0
1  BSM_20170724_11080200.pt  BSM        0.0        0.0    0.030510        0.0
2  BSM_20170724_11370200.pt  BSM        0.0        0.0    0.044483        0.0
3  BSM_20170724_12400100.pt  BSM        0.0        0.0    0.001894        0.0
4  BSM_20170724_12400300.pt  BSM        0.0        0.0    0.002130        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  Whistle_true  \
0        0.0    0.006949        0.0        0.0  8.000287e-02           0.0
1        0.0    0.001860        0.0        0.0  3.540331e-01           0.0
2        0.0    0.004225        0.0        0.0  2.053642e-03           0.0
3        0.0    0.000217        0.0        0.0  7.950342e-06           0.0
4        0.0    0.000004        0.0        0.0  2.440573e-07           0.0

   Whistle_pred  Whistle_probs
0           0.0   2.393886e-01
1           0.0   8.705942e-03
2           0.0   6.423888e-04
3           0.0   3.962404e-05
4           0.0   4.563635e-08

### Leave One Site out

In [24]:


# all_sites = ["BSM", "RDL", "CAC", "KAM" ]
all_sites = [ "RDL", "CAC", "KAM" ]

use_quantization = False

for out_site in all_sites:
    for fold_idx in range(5):
        
        model_class = load_mobilenet_v3_quant if use_quantization else MobileNetMultilabel

        model = model_class(
            pretrained=True,
            n_layers=8,
            num_classes=len(label_columns)
        )

        train_sites = [site for site in all_sites if site != out_site]

        train_df = labels_df[labels_df["test_fold_idx"] != fold_idx]
        
        train_sites_df = train_df[train_df["Site"].isin(train_sites)]

        train_data, val_data = train_test_split(train_sites_df, test_size=0.2, random_state=42, stratify=train_sites_df['Site'])
        
        test_data = labels_df[labels_df["test_fold_idx"] == fold_idx]


        run_name = f"leave_{out_site}_out"
        if use_quantization:
            run_name = run_name + "_qat"

        print(run_name)
        print(f"Site out : {out_site}")
        print("Train df")
        print(train_data["Site"].value_counts())
        print("\nVal df")
        print(val_data["Site"].value_counts())

        # break
        run_dir, _, _ = train_model(
            labels_df,
            label_columns,
            model,
            train_data,
            val_data,
            test_data,
            processed_spects_dir=processed_spects_dir,
            fold_idx=fold_idx,
            run_name=run_name,
            results_dir="./results/sites_generalization_no_bsm",
            training_config=training_config_default,
            use_quantization=use_quantization,
            
        )
    
    aggregate_folds_testing_metrics(run_dir)

    # break

Val Epoch: 25

100%|██████████| 20/20 [00:01<00:00, 14.73it/s]

Val Epoch: 25 Results -
loss: 25.708,
accuracy: {'Labels_Average': 0.952305257320404, 'ECHO': 0.9554848670959473, 'HFPC': 0.9825119376182556, 'BBPC': 0.9650238752365112, 'Whistle': 0.9062002897262573},
f1: {'Labels_Average': 0.89054936170578, 'ECHO': 0.9385964870452881, 'HFPC': 0.904347836971283, 'BBPC': 0.8225806355476379, 'Whistle': 0.8966724872589111},
precision: {'Labels_Average': 0.8815526366233826, 'ECHO': 0.9385964870452881, 'HFPC': 0.8524590134620667, 'BBPC': 0.8644067645072937, 'Whistle': 0.8707482814788818},
recall: {'Labels_Average': 0.9025906324386597, 'ECHO': 0.9385964870452881, 'HFPC': 0.9629629850387573, 'BBPC': 0.7846153974533081, 'Whistle': 0.9241877198219299},
AUC: {'Labels_Average': 0.9816229343414307, 'ECHO': 0.9861584901809692, 'HFPC': 0.9958454370498657, 'BBPC': 0.9739225506782532, 'Whistle': 0.9705653786659241},
exact_match: {'Labels_Average': 0.8314785361289978},

Training Epoch: 26

100%|██████████| 79/79 [00:07<00:00, 11.23it/s]

Train Epoch: 26 Results -
loss: 1.098,
accuracy: {'Labels_Average': 0.997714638710022, 'ECHO': 0.995230495929718, 'HFPC': 0.9988076090812683, 'BBPC': 0.9980127215385437, 'Whistle': 0.9988076090812683},
f1: {'Labels_Average': 0.9942843317985535, 'ECHO': 0.9937499761581421, 'HFPC': 0.9928740859031677, 'BBPC': 0.9917080998420715, 'Whistle': 0.9988052845001221},
precision: {'Labels_Average': 0.9948363900184631, 'ECHO': 0.9937499761581421, 'HFPC': 0.9905213117599487, 'BBPC': 0.996666669845581, 'Whistle': 0.9984076619148254},
recall: {'Labels_Average': 0.9937474727630615, 'ECHO': 0.9937499761581421, 'HFPC': 0.9952380657196045, 'BBPC': 0.9867987036705017, 'Whistle': 0.9992032051086426},
AUC: {'Labels_Average': 0.9999399185180664, 'ECHO': 0.999882161617279, 'HFPC': 0.9998987913131714, 'BBPC': 0.9999850988388062, 'Whistle': 0.999993622303009},
exact_match: {'Labels_Average': 0.9908584952354431},

Val Epoch: 26

100%|██████████| 20/20 [00:01<00:00, 14.87it/s]

Val Epoch: 26 Results -
loss: 26.276,
accuracy: {'Labels_Average': 0.952305257320404, 'ECHO': 0.9507154226303101, 'HFPC': 0.9809221029281616, 'BBPC': 0.9650238752365112, 'Whistle': 0.9125596284866333},
f1: {'Labels_Average': 0.8879039287567139, 'ECHO': 0.9300225973129272, 'HFPC': 0.8928571343421936, 'BBPC': 0.8253968358039856, 'Whistle': 0.9033392071723938},
precision: {'Labels_Average': 0.888201117515564, 'ECHO': 0.9581395387649536, 'HFPC': 0.8620689511299133, 'BBPC': 0.8524590134620667, 'Whistle': 0.8801369667053223},
recall: {'Labels_Average': 0.8893080949783325, 'ECHO': 0.9035087823867798, 'HFPC': 0.9259259104728699, 'BBPC': 0.800000011920929, 'Whistle': 0.9277978539466858},
AUC: {'Labels_Average': 0.9810156226158142, 'ECHO': 0.9837796092033386, 'HFPC': 0.9957810044288635, 'BBPC': 0.9711675047874451, 'Whistle': 0.9733344316482544},
exact_match: {'Labels_Average': 0.8314785361289978},
No improvement over last 5 epochs in validation loss. Early stopping...
Training complete. Loading best model weights.
Training complete in 3m 51s

Test Epoch: 0

100%|██████████| 48/48 [00:03<00:00, 12.05it/s]

Test Epoch: 0 Results -
loss: 60.339,
accuracy: {'Labels_Average': 0.8799934387207031, 'ECHO': 0.8939096331596375, 'HFPC': 0.9757694602012634, 'BBPC': 0.8441388607025146, 'Whistle': 0.8061558604240417},
f1: {'Labels_Average': 0.7463117837905884, 'ECHO': 0.8977272510528564, 'HFPC': 0.7836257219314575, 'BBPC': 0.5369649529457092, 'Whistle': 0.7669291496276855},
precision: {'Labels_Average': 0.7135012149810791, 'ECHO': 0.9647218585014343, 'HFPC': 0.8170731663703918, 'BBPC': 0.39769452810287476, 'Whistle': 0.6745152473449707},
recall: {'Labels_Average': 0.8268189430236816, 'ECHO': 0.8394333124160767, 'HFPC': 0.7528089880943298, 'BBPC': 0.826347291469574, 'Whistle': 0.8886861205101013},
AUC: {'Labels_Average': 0.9455249905586243, 'ECHO': 0.9660905599594116, 'HFPC': 0.9716054201126099, 'BBPC': 0.9265674352645874, 'Whistle': 0.917836606502533},
exact_match: {'Labels_Average': 0.6561886072158813},
Final test loss: 60.3385
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  CAC_20210714_08002300.pt  CAC        1.0        1.0    0.999958        0.0
1  CAC_20210714_08002800.pt  CAC        1.0        1.0    0.999994        0.0
2  CAC_20210714_08003400.pt  CAC        1.0        1.0    0.999916        0.0
3  CAC_20210714_08003600.pt  CAC        1.0        1.0    0.622296        0.0
4  CAC_20210714_08004400.pt  CAC        1.0        1.0    0.999850        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0    0.000175        0.0        0.0    0.000322           1.0
1        0.0    0.000008        0.0        0.0    0.000001           1.0
2        0.0    0.000067        0.0        0.0    0.000022           1.0
3        0.0    0.000032        0.0        0.0    0.000013           1.0
4        0.0    0.000655        1.0        1.0    0.998215           1.0

   Whistle_pred  Whistle_probs
0           1.0       0.997421
1           1.0       0.999995
2           1.0       0.999956
3           1.0       0.999998
4           1.0       0.903004
Size (MB): 0.886346
Size (KB): 865.572265625
Created test dataloader for site: CAC with 657 samples

Test on site cac Epoch: 0

100%|██████████| 21/21 [00:02<00:00, 10.32it/s]

Test on site cac Epoch: 0 Results -
loss: 28.945,
accuracy: {'Labels_Average': 0.9505327343940735, 'ECHO': 0.9406392574310303, 'HFPC': 0.9847792983055115, 'BBPC': 0.9665144681930542, 'Whistle': 0.9101978540420532},
f1: {'Labels_Average': 0.8761004209518433, 'ECHO': 0.9239766001701355, 'HFPC': 0.84375, 'BBPC': 0.8253968358039856, 'Whistle': 0.9112781882286072},
precision: {'Labels_Average': 0.9098043441772461, 'ECHO': 0.9595141410827637, 'HFPC': 0.8999999761581421, 'BBPC': 0.8387096524238586, 'Whistle': 0.9409937858581543},
recall: {'Labels_Average': 0.8452442288398743, 'ECHO': 0.8909774422645569, 'HFPC': 0.7941176295280457, 'BBPC': 0.8125, 'Whistle': 0.8833819031715393},
AUC: {'Labels_Average': 0.9744966626167297, 'ECHO': 0.9805299043655396, 'HFPC': 0.9796053171157837, 'BBPC': 0.9735982418060303, 'Whistle': 0.9642531871795654},
exact_match: {'Labels_Average': 0.8219178318977356},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  CAC_20210714_08002300.pt  CAC        1.0        1.0    0.999958        0.0
1  CAC_20210714_08002800.pt  CAC        1.0        1.0    0.999994        0.0
2  CAC_20210714_08003400.pt  CAC        1.0        1.0    0.999916        0.0
3  CAC_20210714_08003600.pt  CAC        1.0        1.0    0.622296        0.0
4  CAC_20210714_08004400.pt  CAC        1.0        1.0    0.999850        0.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        0.0    0.000175        0.0        0.0    0.000322           1.0
1        0.0    0.000008        0.0        0.0    0.000001           1.0
2        0.0    0.000067        0.0        0.0    0.000022           1.0
3        0.0    0.000032        0.0        0.0    0.000013           1.0
4        0.0    0.000655        1.0        1.0    0.998215           1.0

   Whistle_pred  Whistle_probs
0           1.0       0.997421
1           1.0       0.999995
2           1.0       0.999956
3           1.0       0.999998
4           1.0       0.903004
Created test dataloader for site: KAM with 741 samples

Test on site kam Epoch: 0

100%|██████████| 24/24 [00:01<00:00, 13.00it/s]

Test on site kam Epoch: 0 Results -
loss: 88.941,
accuracy: {'Labels_Average': 0.8090418577194214, 'ECHO': 0.8475033640861511, 'HFPC': 0.9757084846496582, 'BBPC': 0.7206477522850037, 'Whistle': 0.692307710647583},
f1: {'Labels_Average': 0.6114455461502075, 'ECHO': 0.8871129155158997, 'HFPC': 0.6666666865348816, 'BBPC': 0.36307692527770996, 'Whistle': 0.5289255976676941},
precision: {'Labels_Average': 0.5844823718070984, 'ECHO': 0.9758241772651672, 'HFPC': 0.75, 'BBPC': 0.23228345811367035, 'Whistle': 0.3798219561576843},
recall: {'Labels_Average': 0.7787302732467651, 'ECHO': 0.8131868243217468, 'HFPC': 0.6000000238418579, 'BBPC': 0.8309859037399292, 'Whistle': 0.8707482814788818},
AUC: {'Labels_Average': 0.9093672633171082, 'ECHO': 0.9538460969924927, 'HFPC': 0.9503985047340393, 'BBPC': 0.8810174465179443, 'Whistle': 0.8522069454193115},
exact_match: {'Labels_Average': 0.4912280738353729},
                   Filename Site  ECHO_true  ECHO_pred  ECHO_probs  HFPC_true  \
0  KAM_20200722_15003688.pt  KAM        1.0        0.0    0.040485        1.0
1  KAM_20200722_15024396.pt  KAM        0.0        0.0    0.004449        0.0
2  KAM_20200722_15042061.pt  KAM        0.0        1.0    0.905062        0.0
3  KAM_20200722_15060709.pt  KAM        1.0        1.0    0.986598        1.0
4  KAM_20200722_15070459.pt  KAM        1.0        1.0    0.999583        1.0

   HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred  BBPC_probs  Whistle_true  \
0        1.0    0.999378        0.0        0.0    0.007243           1.0
1        0.0    0.000021        0.0        0.0    0.000164           1.0
2        0.0    0.000334        0.0        1.0    0.999997           1.0
3        1.0    0.968508        0.0        1.0    0.731991           1.0
4        0.0    0.043227        0.0        0.0    0.000007           0.0

   Whistle_pred  Whistle_probs
0           1.0       0.998278
1           1.0       0.999999
2           1.0       0.999997
3           1.0       0.995323
4           0.0       0.000002
Created test dataloader for site: RDL with 129 samples

Test on site rdl Epoch: 0

100%|██████████| 5/5 [00:00<00:00, 14.50it/s]

Test on site rdl Epoch: 0 Results -
loss: 30.768,
accuracy: {'Labels_Average': 0.9282945990562439, 'ECHO': 0.9224806427955627, 'HFPC': 0.930232584476471, 'BBPC': 0.930232584476471, 'Whistle': 0.930232584476471},
f1: {'Labels_Average': 0.8675235509872437, 'ECHO': 0.8571428656578064, 'HFPC': 0.8301886916160583, 'BBPC': 0.8571428656578064, 'Whistle': 0.9256198406219482},
precision: {'Labels_Average': 0.8506784439086914, 'ECHO': 0.8571428656578064, 'HFPC': 0.7857142686843872, 'BBPC': 0.8709677457809448, 'Whistle': 0.8888888955116272},
recall: {'Labels_Average': 0.886602520942688, 'ECHO': 0.8571428656578064, 'HFPC': 0.8799999952316284, 'BBPC': 0.84375, 'Whistle': 0.9655172228813171},
AUC: {'Labels_Average': 0.9668694734573364, 'ECHO': 0.9410334825515747, 'HFPC': 0.9711538553237915, 'BBPC': 0.9732603430747986, 'Whistle': 0.9820300936698914},
exact_match: {'Labels_Average': 0.7596899271011353},
                   Filename Site  ECHO_true  ECHO_pred    ECHO_probs  \
0  RDL_20200722_10422986.pt  RDL        0.0        0.0  6.050639e-07
1  RDL_20200722_10423086.pt  RDL        0.0        0.0  4.634737e-05
2  RDL_20200722_10513900.pt  RDL        0.0        0.0  2.041073e-03
3  RDL_20200722_10515900.pt  RDL        0.0        0.0  7.094609e-05
4  RDL_20200722_10521300.pt  RDL        0.0        0.0  3.342741e-04

   HFPC_true  HFPC_pred  HFPC_probs  BBPC_true  BBPC_pred    BBPC_probs  \
0        0.0        0.0    0.000004        0.0        0.0  2.819466e-07
1        0.0        0.0    0.000044        0.0        0.0  1.146987e-04
2        0.0        0.0    0.005680        1.0        1.0  9.984202e-01
3        0.0        0.0    0.000155        1.0        1.0  9.999446e-01
4        0.0        0.0    0.000063        0.0        0.0  1.166876e-05

   Whistle_true  Whistle_pred  Whistle_probs
0           0.0           0.0       0.000009
1           0.0           0.0       0.000251
2           1.0           1.0       0.999224
3           1.0           1.0       0.999854
4           0.0           0.0       0.000244

<h2>Training the final model on all the data</h2>

In [ ]:
from training.cross_validation import create_test_fold_indices
from sklearn.model_selection import KFold, train_test_split
from models.utils import aggregate_folds_testing_metrics



labels_df = pd.read_csv("../data/labels/Overlaps_1s.csv")
labels_df["ClipFilenamePt"] = labels_df["ClipFilename"] + ".pt"


label_columns = ["ECHO", "HFPC", "CC", "Whistle"]

data_dir = "../data"
processed_spects_dir = data_dir + "/Full_Dataset/Overlaps_1s_hp_1024_resize/"

results_dir = "./final_results"

labels_df = create_test_fold_indices(labels_df, 5)

In [ ]:

use_quantization = True
        
model_class = load_mobilenet_v3_quant if use_quantization else MobileNetMultilabel

model = model_class(
    pretrained=True,
    n_layers=8,
    num_classes=len(label_columns)
)

train_data, val_data = train_test_split(train_data, test_size=0.2, random_state=42, stratify=train_data['Site'])
test_data = val_data #Doesn't matter here, won't be used anyway

run_name = f"Final_model"
if use_quantization:
    run_name = run_name + "_qat"

run_dir = train_model(
    labels_df,
    label_columns,
    model,
    train_data,
    val_data,
    test_data,
    fold_idx=0,
    processed_spects_dir=processed_spects_dir,
    run_name=run_name,
    results_dir="results/final_model",
    training_config=training_config_default,
    use_quantization=use_quantization,
    save_model=True
)